config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "products#index"
  # post 'carts/:id' => "carts#create"

  resources :products do 
    collection { post :import }
  end
  resources :carts

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :cart, optional: true

    def self.import(file)
        CSV.foreach(file.path, headers: true) do |row|
            # product = Product.find_by(row["id"])
            # product = Product.find_by_id([:id])
            # if product.present?
                # next
            # else
                # Product.create! row.to_hash
                Product.find_or_create_by row.to_hash
            # end
        end
    end
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    # before_action :current_cart

    # private
    #   def current_cart
    #     if session[:cart_id]
    #       cart = Cart.find_by(:id => session[:cart_id])
    #       if cart.present?
    #         @current_cart = cart
    #       else
    #         session[:cart_id] = nil
    #       end
    #     end
  
    #     if session[:cart_id] == nil
    #       @current_cart = Cart.create
    #       session[:cart_id] = @current_cart.id
    #     end
    #   end
     
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
    @carts = Cart.all
    # @carts = @product

  end
  
  def new
    @cart = Cart.new
  end

  def create
    @cart = Cart.new
    @cart.quantity = params[:quantity]
    @cart.products << Product.find(params[:product_id])

    #@cart = Cart.create(cart_params)
    @cart.save
    redirect_to products_path
  end

  def show
    @cart = @current_cart
  end

  def destroy
    @cart = @current_cart
    @cart.destroy

    session[:cart_id] = nil
    
    redirect_to root_path
  end

  private
  def cart_params
    params.require(:cart).permit(:product_id, :quantity)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    @cart = Cart.new
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.create(product_params)
    redirect_to products_path
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update(product_params)
    redirect_to products_path
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  def import
    Product.import(params[:file])
    redirect_to products_path, notice: "Products added"
  end

  private
    def product_params
      params.require(:product).permit(:name, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/create.html.erb
      
<h2>Create new Subject</h2>

    <%= @product.name %>

<%= number_to_currency(@product.price) %>


   

<%= form_for :cart, url: carts_path do |f| %>

    <%= f.label :Quantity %>

    <%= f.number_field :quantity, required: true %>

    <%= f.submit "Create Now!" %>

<% end %>

app/views/carts/index.html.erb
<br /><br /><br />

<h2>All Products</h2>

<br />

<br />

<% Cart.all.each do |cart| %>
  <p>Name: <%= cart.products %> </p>

  <%= cart.quantity %>
  <p>
    <%= link_to "Edit", edit_cart_path(cart) %> |
    <%= link_to "Delete", cart_path(cart), method: :delete, data: {confirm: "Are you sure?"} %>
    
  </p>
<% end%>

app/views/carts/show.html.erb
<h2>Cart show</h2>
<ul>
  <% @cart.line_items.each do |line_item| %>
    <li>Item: <%= line_item.product.name %>/ Price: <%= number_to_currency(line_item.product.price) %>/ Quantity: <%= line_item.quantity %>/ Total Price: <%= number_to_currency(line_item.total_price) %>
    # See lineItem section below for explanation of line_item links
    <ul>
      <li>
        <%= link_to "Add one", line_item_add_path(:id => line_item), method: :post %>
        <%= link_to "Reduce one", line_item_reduce_path(:id => line_item), method: :post %>
      </li>
      <li>
        <%= link_to "Remove item", line_item_path(line_item), method: :delete %>
      </li>
    </ul>
    #
  <% end %>
</ul>
<h3>Sub total: <%= number_to_currency(@cart.sub_total) %></h3>
# See Order section below for explanation of new_order_path
<%= link_to "Proceed to checkout", new_order_path %><br>
#
<%= link_to "Empty cart", cart_path(@current_cart),method: :delete, data: {confirm: "Are you sure?"} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AndJoy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <% if user_signed_in? %> 
        <div style="float:right; font-size:25px; margin: 70px;"><%= link_to "Sign out", destroy_user_session_path %></div>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>

app/views/products/index.html.erb
<br /><br /><br />

<h2>All Products</h2>

<br />

<%= link_to "New product", new_product_path %>

<h3>Import Products</h3>
<%= form_tag import_products_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Upload" %>
<% end %>

<br />

<br />

<% @products.each do |product| %>
  <p>Name: <%= product.name %>; unit price of <%= number_to_currency(product.price) %></p>
  <p>
    <%= link_to "Edit", edit_product_path(product) %> |
    <%= link_to "Delete", product_path(product), method: :delete, data: {confirm: "Are you sure?"} %>
  
    <%= form_for(@cart) do |f| %>
      <%= hidden_field_tag :product_id, product.id %>
      <%= hidden_field_tag :quantity, 1 %>
      <%= f.submit %>
  <% end %>
    
  </p>
<% end%>

app/views/products/new.html.erb
<%= form_for(@product) do |f| %>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name, required: true, autofocus: true, placeholder: "Enter product name" %>
    </p>
    <p>
      <%= f.label :price %><br>
      <%= f.number_field :price, required: true %>
    </p>
    <p>
      <%= f.submit %>
    </p>
  <% end %>